### PR TITLE
Initial multiplayer support with SDL net (TCP).

### PR DESCRIPTION
**Pull request by veikkos**
PR's content

- ~Currently hard-coded to join to localhost - UI will be implemented in separate PR to scope the already big PR.~ (Edit: implemented simple UI for server IP address input)
- Fix more than 1 client joining - original code didn't propagate joining to existing clients.
- Refactor player data serialization and deserialization to separate functions - re-used with new IPX_NEWPLAYERDATA message.
- Disconnect message IPX_PLAYERDISCONNECTED - allows clients to know about disconnects which original code had ignored.

Still many references to IPX in code - in my opinion changing them all in this PR would have created too big changeset so I propose that we change them in separate PR.

Things to improve in next PRs
- ~UI for selecting server IP address~
- ~Better UX if server is missing when joining as a client (now application closes)~ (Edit: Now UI timeouts after a while and returns to main menu)
- Code cleanup, e.g. replace all IPX references
- Probably robustness fixes but it doesn't actually seem too bad now - doesn't like blocking like if holding window on Windows at least

### CODE REVIEW

**Comment by veikkos** [comment]
There is some SDL initialization issue with Linux and some warnings - I'll address those still.

**Comment by veikkos** [comment]
Now it is working without warnings on Linux as well.

Unfortunately had to do heavy renaming (name clash with variable "send") and fix many warnings in previously ifdeffed network code so GAME.CPP diff is quite huge.

We can do more cleanup but as said in the description I'd rather not add more to this PR to avoid it getting out of hand. Please let me know if you disagree.

**Comment by veikkos** [comment]
Implemented UI for server IP address input for clients. Now it's proper MVP.

**Comment by akheron** [comment]
Thanks, great work!

Unfortunately doesn't compile for me on gcc 8.2.1, there are quite many errors. Seems that travis uses gcc 4.8 which is a tad older :D 

Compiler output: [build.txt](https://github.com/suomipelit/ultimatetapankaikki/files/2679199/build.txt)

**Comment by veikkos** [comment]
Thanks for the input! I have oldish Ubuntu LTS so oldish compiler as well. I'll fix the issues soon.

**Comment by veikkos** [comment]
> Unfortunately doesn't compile for me on gcc 8.2.1

Fixed those compilation issues. I opened PR #44 which adds automated GCC 8 build to Travis to avoid it in the future. Was also good time to update my ancient GCC. :)

**Pull request merged**
